// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectPostToolUseAcceptanceCapability } from "./DirectPostToolUseAcceptanceCapability";

export type CodeModeOutputReducerAcceptanceCapability = { descriptorUrlField: string, responseIdField: string, callbackVersion: number, directPostToolUse: DirectPostToolUseAcceptanceCapability, };
