// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeModeOutputReducerAcceptanceCapability } from "./CodeModeOutputReducerAcceptanceCapability";

export type CodeModeOutputReducerCapability = { protocolVersion: number, configKey: string, maxOutputTokensCeilingConfigKey: string, postToolUseNestedContextField: string, supportsThreadResumeOverrides: boolean, dynamicToolsResumeField: string, acceptance: CodeModeOutputReducerAcceptanceCapability, };
