// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PwrdrvrTokenMiserCapability = { version: number, identity: string, initializeCapabilityField: string, threadStartField: string, threadResumeField: string, descriptorEnvironmentVariable: string, descriptorVersion: number, };
