// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodeModeOutputReducerCapability } from "./CodeModeOutputReducerCapability";
import type { PwrdrvrTokenMiserCapability } from "./PwrdrvrTokenMiserCapability";

export type ServerCapabilitiesReadResponse = { codeModeOutputReducer: CodeModeOutputReducerCapability, pwrdrvrTokenMiser: PwrdrvrTokenMiserCapability, };
